In [1]:
import pandas as pd
import numpy as np

In [9]:
my_list = [10,20,30]
a = np.array([10,20,30])
d = { 1:10 , 2:20,3:30 }

In [7]:
pd.Series(a)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# DataFrame

In [19]:
data = {
    'name' : ["ved" , "Jeel" , "kashyap" , "Het"] ,
    'age' : [20 , 21 , 30 , 19],
    'city' : ["New York" , "Paris" , "Berlin" , "London"],
    'Salary' : [100000 , 65000 , 5000 , 34000]
}

pd.DataFrame(data)

      name  age      city  Salary
0      ved   20  New York  100000
1     Jeel   21     Paris   65000
2  kashyap   30    Berlin    5000
3      Het   19    London   34000

In [20]:
data_list = [
    ["ved" , 20 , "New York" , 100000],
    ["jeel" , 21 , "Paris" , 50000] ,
    ["het" , 20 , "barlin" , 10000]
]

pd.DataFrame(data_list)

      0   1         2       3
0   ved  20  New York  100000
1  jeel  21     Paris   50000
2   het  20    barlin   10000

In [21]:
columns = ["Name" , "age" , "City" , "salary"]

pd.DataFrame(data_list , columns=columns)

   Name  age      City  salary
0   ved   20  New York  100000
1  jeel   21     Paris   50000
2   het   20    barlin   10000

## Selection in dataFrame

In [23]:
df = pd.DataFrame(data)
df

      name  age      city  Salary
0      ved   20  New York  100000
1     Jeel   21     Paris   65000
2  kashyap   30    Berlin    5000
3      Het   19    London   34000

In [24]:
df["city"]

0    New York
1       Paris
2      Berlin
3      London
Name: city, dtype: object

In [ ]:
df[ [ "name" , "city" ] ]

      name      city
0      ved  New York
1     Jeel     Paris
2  kashyap    Berlin
3      Het    London

## creating new column

In [26]:
df["Designation"] = [ "Eng." , "Doctor" , "Eng." , "Teacher" ]

df

      name  age      city  Salary Designation
0      ved   20  New York  100000        Eng.
1     Jeel   21     Paris   65000      Doctor
2  kashyap   30    Berlin    5000        Eng.
3      Het   19    London   34000     Teacher

In [ ]:
df.drop( 'Designation' , axis=1 )  # must give axis = 1

      name  age      city  Salary
0      ved   20  New York  100000
1     Jeel   21     Paris   65000
2  kashyap   30    Berlin    5000
3      Het   19    London   34000

In [ ]:
df  # drop don't drop permenentlyy

      name  age      city  Salary Designation
0      ved   20  New York  100000        Eng.
1     Jeel   21     Paris   65000      Doctor
2  kashyap   30    Berlin    5000        Eng.
3      Het   19    London   34000     Teacher

In [ ]:
df.drop( "Designation" , axis= 1 , inplace= True )  # give inplace inplace = True to permenent delete

In [31]:
df

      name  age      city  Salary
0      ved   20  New York  100000
1     Jeel   21     Paris   65000
2  kashyap   30    Berlin    5000
3      Het   19    London   34000

In [32]:
df.drop( [ "city" , "name" ] , axis= 1 )

   age  Salary
0   20  100000
1   21   65000
2   30    5000
3   19   34000

In [33]:
df.drop( 0 )

      name  age    city  Salary
1     Jeel   21   Paris   65000
2  kashyap   30  Berlin    5000
3      Het   19  London   34000

In [34]:
df.drop( [0 , 2] )

   name  age    city  Salary
1  Jeel   21   Paris   65000
3   Het   19  London   34000

In [35]:
df

      name  age      city  Salary
0      ved   20  New York  100000
1     Jeel   21     Paris   65000
2  kashyap   30    Berlin    5000
3      Het   19    London   34000

In [36]:
df.loc[0]

name           ved
age             20
city      New York
Salary      100000
Name: 0, dtype: object

In [37]:
df.loc[ [0,1] ]

   name  age      city  Salary
0   ved   20  New York  100000
1  Jeel   21     Paris   65000

In [38]:
df.iloc[ 3 ]

name         Het
age           19
city      London
Salary     34000
Name: 3, dtype: object

In [39]:
df

      name  age      city  Salary
0      ved   20  New York  100000
1     Jeel   21     Paris   65000
2  kashyap   30    Berlin    5000
3      Het   19    London   34000

## selecting subset of rows & cols

In [40]:
df

      name  age      city  Salary
0      ved   20  New York  100000
1     Jeel   21     Paris   65000
2  kashyap   30    Berlin    5000
3      Het   19    London   34000

In [41]:
df.loc [ [0,1] ] [ ["city" , "Salary"] ]

       city  Salary
0  New York  100000
1     Paris   65000

In [43]:
df.loc [ [2,3] ] [ ["name" , "age"] ]

      name  age
2  kashyap   30
3      Het   19

## Conditional Selection

In [44]:
df

      name  age      city  Salary
0      ved   20  New York  100000
1     Jeel   21     Paris   65000
2  kashyap   30    Berlin    5000
3      Het   19    London   34000

In [45]:
# i only want to see whose age is less then 21

In [46]:
df [ df["age"] < 21 ]

  name  age      city  Salary
0  ved   20  New York  100000
3  Het   19    London   34000

In [ ]:
# whose age less then 21 & city is New York
df[ (df["age"] < 21) & (df["city"] == "New York") ]

  name  age      city  Salary
0  ved   20  New York  100000

# Finding missing Data

In [51]:
data = {
    "a" : [1,2,np.nan , 4,5],
    "b" : [np.nan , 2,3,4,5],
    "c" : [1,2,3,np.nan , np.nan],
    "d" : [1,np.nan , np.nan , np.nan , 5]
}
df = pd.DataFrame(data)
df

     a    b    c    d
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [52]:
df.isna()

       a      b      c      d
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum() # how many null value in that row

a    1
b    1
c    2
d    3
dtype: int64

In [ ]:
df.isna().any() # is that row contain null value

a    True
b    True
c    True
d    True
dtype: bool

# Removing null value

In [55]:
df

     a    b    c    d
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.dropna() # give rows which has all not null value

Empty DataFrame
Columns: [a, b, c, d]
Index: []

In [ ]:
df.dropna(thresh=3) # give that rows which has atleast 3 not null value

     a    b    c    d
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [60]:
df.dropna(thresh=2) # give that rows which has atleast 2 not null value

     a    b    c    d
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

# filling tha missing data

In [61]:
df

     a    b    c    d
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.fillna(0) # replace null value by 0

     a    b    c    d
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [63]:
values = { "a" : 0 , "b" : 100 , "c" : 24.5  , "d" : 5}

df.fillna(value=values)

     a      b     c    d
0  1.0  100.0   1.0  1.0
1  2.0    2.0   2.0  5.0
2  0.0    3.0   3.0  5.0
3  4.0    4.0  24.5  5.0
4  5.0    5.0  24.5  5.0

In [65]:
df

     a    b    c    d
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [66]:
df.fillna( df.mean() )

     a    b    c    d
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

# Merging 2 DataFrames

In [69]:
# dataframe 1
emp = pd.DataFrame( {
    "emp_id" : [1,2,3,4,5],
    "name" : [ "e1" , "e2" , "e3" , "e4" , "e5" ],
    "dept" : [  "HR" , "IT" , "Finance" , "IT" , "HR" ]
} )

# dataframe 2
sal = pd.DataFrame( {
    "emp_id" : [1,2,3,6,7] ,
    "salary" : [60000 , 10000 , 20000 , 13000 , 67000],
    "bonus" : [3000 , 1000 , 10000 , 500 , 3400]
} )

In [70]:
emp

   emp_id name     dept
0       1   e1       HR
1       2   e2       IT
2       3   e3  Finance
3       4   e4       IT
4       5   e5       HR

In [71]:
sal

   emp_id  salary  bonus
0       1   60000   3000
1       2   10000   1000
2       3   20000  10000
3       6   13000    500
4       7   67000   3400

In [ ]:
pd.merge( emp , sal ) # on same column

   emp_id name     dept  salary  bonus
0       1   e1       HR   60000   3000
1       2   e2       IT   10000   1000
2       3   e3  Finance   20000  10000

In [73]:
pd.merge( emp , sal  , how="inner")

   emp_id name     dept  salary  bonus
0       1   e1       HR   60000   3000
1       2   e2       IT   10000   1000
2       3   e3  Finance   20000  10000

In [74]:
pd.merge( emp , sal  , how="outer")

   emp_id name     dept   salary    bonus
0       1   e1       HR  60000.0   3000.0
1       2   e2       IT  10000.0   1000.0
2       3   e3  Finance  20000.0  10000.0
3       4   e4       IT      NaN      NaN
4       5   e5       HR      NaN      NaN
5       6  NaN      NaN  13000.0    500.0
6       7  NaN      NaN  67000.0   3400.0

In [ ]:
pd.merge( emp , sal  , how="left")

   emp_id name     dept   salary    bonus
0       1   e1       HR  60000.0   3000.0
1       2   e2       IT  10000.0   1000.0
2       3   e3  Finance  20000.0  10000.0
3       4   e4       IT      NaN      NaN
4       5   e5       HR      NaN      NaN

In [76]:
pd.merge( emp , sal  , how="right")

   emp_id name     dept  salary  bonus
0       1   e1       HR   60000   3000
1       2   e2       IT   10000   1000
2       3   e3  Finance   20000  10000
3       6  NaN      NaN   13000    500
4       7  NaN      NaN   67000   3400

# Concatination of 2 dataframes

In [84]:
df1 = pd.DataFrame( {
    "a" : ["a0" , "a1" , "a2"],
    "b" : ["b0" , "b1" , "b2"],
    "c" : ["c0" , "c1" , "c2"]
} )

df2 = pd.DataFrame( {
    "a" : ["a3" , "a4" , "a5"],
    "b" : ["b3" , "b4" , "b5"],
    "c" : ["c3" , "c4" , "c5"]
} )

In [78]:
df1

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2

In [82]:
df2

    a   b   d
0  a3  b3  c3
1  a4  b4  c4
2  a5  b5  c5

In [85]:
pd.concat( [ df1 , df2 ] )

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
0  a3  b3  c3
1  a4  b4  c4
2  a5  b5  c5

In [86]:
pd.concat( [df1 , df2] , axis=1 )

    a   b   c   a   b   c
0  a0  b0  c0  a3  b3  c3
1  a1  b1  c1  a4  b4  c4
2  a2  b2  c2  a5  b5  c5

# Joinging 2 dataframe

In [89]:
df1 = pd.DataFrame( {
    "name" : [ "ved" , 'jeel' , 'het' ]
} , index=[1,2,3] )

df2 = pd.DataFrame( {
    "score" : [ 381 , 355 , 290 ]
} , index=[2,3 , 4] )

In [90]:
df1

   name
1   ved
2  jeel
3   het

In [91]:
df2

   score
2    381
3    355
4    290

In [92]:
df1.join(df2)

   name  score
1   ved    NaN
2  jeel  381.0
3   het  355.0

In [93]:
df1.join(df2 , how="outer")

   name  score
1   ved    NaN
2  jeel  381.0
3   het  355.0
4   NaN  290.0

# Group By

In [4]:
data = {
    'category' : [ 'a' , 'b' , 'a' , 'b' , 'a' , 'b' , 'a' , 'b' ],
    'store' : [ 's1' , 's1' , 's2' , 's2' , 's1' , 's2' , 's2' , 's1' ],
    "sales" : [ 100 , 200 , 150 , 250 , 120 , 180 , 200 , 300 ],
    "quantity" : [10,15,12,18,8,20,15,25],
    "date" : pd.date_range( '2025-01-01' , periods=8)
}

df = pd.DataFrame(data)
df

  category store  sales  quantity       date
0        a    s1    100        10 2025-01-01
1        b    s1    200        15 2025-01-02
2        a    s2    150        12 2025-01-03
3        b    s2    250        18 2025-01-04
4        a    s1    120         8 2025-01-05
5        b    s2    180        20 2025-01-06
6        a    s2    200        15 2025-01-07
7        b    s1    300        25 2025-01-08

In [97]:
# group by category and cal. tha sum of sales

df.groupby( "category" )

In [104]:
cat = df.groupby( "category" )

for i , v in cat :
    print(i)
    print(v)

a
  category store  sales  quantity       date
0        a    s1    100        10 2025-01-01
2        a    s2    150        12 2025-01-03
4        a    s1    120         8 2025-01-05
6        a    s2    200        15 2025-01-07
b
  category store  sales  quantity       date
1        b    s1    200        15 2025-01-02
3        b    s2    250        18 2025-01-04
5        b    s2    180        20 2025-01-06
7        b    s1    300        25 2025-01-08

In [ ]:
cat = df.groupby( "category" )[ "sales"].sum()
cat

category
a    570
b    930
Name: sales, dtype: int64

In [107]:
# group by Store & cal. sum of sales

store = df.groupby( "store" )["sales"].sum()

store

store
s1    720
s2    780
Name: sales, dtype: int64

In [111]:
# groueby multiple columns

store = df.groupby( [ 'category' , 'store' ] )["sales"].sum()
print(store)

category  store
a         s1       220
          s2       350
b         s1       500
          s2       430
Name: sales, dtype: int64

In [112]:
store = df.groupby( [ 'store' , 'category'] )["sales"].sum()
print(store)

store  category
s1     a           220
       b           500
s2     a           350
       b           430
Name: sales, dtype: int64

# Aggregation

In [115]:
mean = df["sales"].mean()
median = df["sales"].median()
mode = df["sales"].mode()
min = df["sales"].min()
max = df["sales"].max()
std = df["sales"].std()

print(mean) 
print(median) 
print(mode) 
print(min) 
print(max) 
print(std)

187.5
190.0
0    200
Name: sales, dtype: int64
100
300
66.06274074155351

In [5]:
df[ ["sales" , "quantity"] ].agg( ["mean" ,  "min" , "max" , "std" , "median"] ) # can't write mode in this

             sales   quantity
mean    187.500000  15.375000
min     100.000000   8.000000
max     300.000000  25.000000
std      66.062741   5.553313
median  190.000000  15.000000

# Pivot Tables

In [ ]:
data = {
    "date" : pd.date_range( '2025-01-01' , periods=20 ),
    "product" : ['a' , 'b' , 'c' , 'd'] * 5,
    "region" : [ 'east' , 'west' , 'north' , 'south' ] * 5 ,
    "sales" : np.random.randint(100 , 1000 , 20),
    "units" : np.random.randint(10,100,20),
    "rep" : [ 'john' , 'mary' , 'bob' , 'alice' ] * 5
}

df = pd.DataFrame(data)
df["month"] = df['date'].dt.month_name()
df["quarter"] = 'Q' + df["date"].dt.quarter.astype(str)

df

         date product region  sales  units    rep    month quarter
0  2025-01-01       a   east    808     22   john  January      Q1
1  2025-01-02       b   west    821     87   mary  January      Q1
2  2025-01-03       c  north    642     25    bob  January      Q1
3  2025-01-04       d  south    771     26  alice  January      Q1
4  2025-01-05       a   east    748     97   john  January      Q1
5  2025-01-06       b   west    123     45   mary  January      Q1
6  2025-01-07       c  north    982     35    bob  January      Q1
7  2025-01-08       d  south    523     25  alice  January      Q1
8  2025-01-09       a   east    372     48   john  January      Q1
9  2025-01-10       b   west    878     97   mary  January      Q1
10 2025-01-11       c  north    550     24    bob  January      Q1
11 2025-01-12       d  south    403     37  alice  January      Q1
12 2025-01-13       a   east    508     23   john  January      Q1
13 2025-01-14       b   west    192     78   mary  January      Q1
14 2025-01-15       c  north    620     95    bob  January      Q1
15 2025-01-16       d  south    542     96  alice  January      Q1
16 2025-01-17       a   east    463     21   john  January      Q1
17 2025-01-18       b   west    254     22   mary  January      Q1
18 2025-01-19       c  north    920     76    bob  January      Q1
19 2025-01-20       d  south    697     37  alice  January      Q1

In [ ]:
pd.pivot_table(df , values="sales" , index="region" , columns= "product" ) # if multiple vales so give mean value for that cell

product      a      b      c      d
region
east     579.8    NaN    NaN    NaN
north      NaN    NaN  742.8    NaN
south      NaN    NaN    NaN  587.2
west       NaN  453.6    NaN    NaN

In [9]:
pd.pivot_table(df , values="sales" , index="region" , columns= "product" , aggfunc="min" )

product      a      b      c      d
region
east     372.0    NaN    NaN    NaN
north      NaN    NaN  550.0    NaN
south      NaN    NaN    NaN  403.0
west       NaN  123.0    NaN    NaN

In [ ]:
pd.pivot_table(df , values="sales" , index="region" , columns= "product" , aggfunc="median" )

product      a      b      c      d
region
east     508.0    NaN    NaN    NaN
north      NaN    NaN  642.0    NaN
south      NaN    NaN    NaN  542.0
west       NaN  254.0    NaN    NaN

In [11]:
pd.pivot_table( df , values=[ "sales" , "units" ] , columns="product" , index="region" )

         sales                      units
product      a      b      c      d     a     b     c     d
region
east     579.8    NaN    NaN    NaN  42.2   NaN   NaN   NaN
north      NaN    NaN  742.8    NaN   NaN   NaN  51.0   NaN
south      NaN    NaN    NaN  587.2   NaN   NaN   NaN  44.2
west       NaN  453.6    NaN    NaN   NaN  65.8   NaN   NaN

In [ ]:
pd.pivot_table( df , values=[ "sales" , "quarter" ] , columns="product" , index="region" ) # this will give error because quarter is not support agg. functions

# Cross Tabs

In [13]:
pd.crosstab( df["region"] , df["product"] )

product  a  b  c  d
region
east     5  0  0  0
north    0  0  5  0
south    0  0  0  5
west     0  5  0  0

# DataFrames Basic Operations

In [14]:
df = pd.DataFrame({
    'a' : [1,2,3,4,5] , 
    "b" : [10,20,30,40,50],
    "c" : [100,200,300,400,500]
})
df

   a   b    c
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [15]:
df.shape

(5, 3)

In [16]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       5 non-null      int64
 1   b       5 non-null      int64
 2   c       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [18]:
df.describe()

              a          b           c
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [19]:
df["a"] + 10

0    11
1    12
2    13
3    14
4    15
Name: a, dtype: int64

In [20]:
df

   a   b    c
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [21]:
def square(x) :
    return x ** 2

In [22]:
df["b"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: b, dtype: int64

In [23]:
df

   a   b    c
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [24]:
df["d"] = df["b"].apply(square)

In [25]:
df

   a   b    c     d
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [26]:
df["d"] = df["d"].apply( lambda x : x /10 )

In [27]:
df

   a   b    c      d
0  1  10  100   10.0
1  2  20  200   40.0
2  3  30  300   90.0
3  4  40  400  160.0
4  5  50  500  250.0

In [2]:
df = pd.read_csv(r"anime.csv")
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [3]:
# make new column for ep. count

def countEp(txt) :
    temp = txt.split("(")

    ep = temp[1].split()

    ep = ep[0]

    return int(ep)

df["ep_count"] = df["Title"].apply(countEp)

df

    Rank                                              Title  Score  ep_count
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04        51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04         1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04       148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04        13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03        13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03         2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02       110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99        13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99        13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98        12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94       201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94         1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93        22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93        24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91        25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91         1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89         1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88         7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88        14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87        74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84         1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84         1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83        12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83         1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82        24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82        23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81        12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81        26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80        13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80        16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79        11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79         1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79        11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78        10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78         1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77        26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77        12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76        75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75        26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75        26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74        24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73        10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72        12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71        12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71         4

In [15]:
# make column for timestamp

def timeStamp(txt) :
    temp = txt.split(")")
    time = temp[1][:19]
    return time

df["timestamp"] = df["Title"].apply(timeStamp)
df

,Rank,Title,Score,ep_count,timestamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [ ]:
# find total months
df['total_months'] = (
    pd.to_datetime(df['timestamp'].str.split(' - ').str[1], format='%b %Y').dt.to_period('M') -
    pd.to_datetime(df['timestamp'].str.split(' - ').str[0], format='%b %Y').dt.to_period('M')
).apply(lambda x: x.n +1)

df

,Rank,Title,Score,ep_count,timestamp,total_months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,12
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,3
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,6
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,3
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,2
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,3
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,3
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,6
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,6
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,6
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,1
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,4
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,3
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,6
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,2
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,3
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,19
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,4
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,4
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,3
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,3
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,3
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,6
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,4
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,13
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,7
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,6
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,3
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,3
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,3
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,8

In [18]:
# give me top highest Scoring anime

df["Title"].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [19]:
# highest ep. count

df[ df["ep_count"] == df["ep_count"].max() ]["Title"]

15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
Name: Title, dtype: object

# Countries

In [20]:
df = pd.read_csv(r"Countries.csv")
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [22]:
# which country has highest population

df[ df["population"] == df["population"].max() ]["country"]

75    India
Name: country, dtype: object

In [23]:
# capital of the country with that highest population

df[ df["population"] == df["population"].max() ]["capital_city"]

75    New Delhi
Name: capital_city, dtype: object

In [24]:
# country with least population

df[ df["population"] == df["population"].min() ]["country"]

179    Tuvalu
Name: country, dtype: object

In [25]:
# capital of the country with that least population

df[ df["population"] == df["population"].min() ]["capital_city"]

179    Funafuti
Name: capital_city, dtype: object

In [28]:
# give me top 5 countries with highest democratic score

df.sort_values( "democracy_score" , ascending=False ).head()["country"]

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [ ]:
# how many total regions are there

len(df["region"].unique())  # method 1
df["region"].value_counts().count() # method 2

np.int64(22)

In [40]:
df[ df["region"] == "Eastern Europe" ] ["country"].count()

np.int64(10)

In [48]:
# who is political leader of second highest populated country

df.sort_values( "population" , ascending=False )["political_leader"].iloc[1]

'Xi Jinping'